only define _LARGEFILE64_SOURCE if not already defined; use texi2html for html docs but fall back on makeinfo

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -730,6 +730,10 @@ LIBGNU_LIBDEPS
 LIBGNU_LTLIBDEPS
 TEXI2DVI
 TEXI2HTML
+HTMLDOCS_TEXI2HTML_TRUE
+HTMLDOCS_TEXI2HTML_FALSE
+HTMLDOCS_MAKEINFO_TRUE
+HTMLDOCS_MAKEINFO_FALSE
 PRODUCT
 HOST
 MAKE
@@ -16845,49 +16849,6 @@ _ACEOF
 
 fi
 
-# Extract the first word of "makeinfo", so it can be a program name with args.
-set dummy makeinfo; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_prog_MAKEINFO+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$MAKEINFO"; then
-  ac_cv_prog_MAKEINFO="$MAKEINFO" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_MAKEINFO="makeinfo"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_prog_MAKEINFO" && ac_cv_prog_MAKEINFO="false"
-fi
-fi
-MAKEINFO=$ac_cv_prog_MAKEINFO
-if test -n "$MAKEINFO"; then
-  { echo "$as_me:$LINENO: result: $MAKEINFO" >&5
-echo "${ECHO_T}$MAKEINFO" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-if test "$MAKEINFO" = "false"; then
-    { echo "$as_me:$LINENO: WARNING: ***** makeinfo utility not found *****" >&5
-echo "$as_me: WARNING: ***** makeinfo utility not found *****" >&2;}
-fi
-
 # Extract the first word of "texi2dvi", so it can be a program name with args.
 set dummy texi2dvi; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -16931,6 +16892,7 @@ if test "$TEXI2DVI" = "false"; then
 echo "$as_me: WARNING: ***** texi2dvi utility not found *****" >&2;}
 fi
 
+htmldocs_texi2html=no
 # Extract the first word of "texi2html", so it can be a program name with args.
 set dummy texi2html; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -16972,7 +16934,75 @@ fi
 if test "$TEXI2HTML" = "false"; then
     { echo "$as_me:$LINENO: WARNING: ***** texi2html utility not found *****" >&5
 echo "$as_me: WARNING: ***** texi2html utility not found *****" >&2;}
+else
+    htmldocs_texi2html=yes
 fi
+
+
+if test "$htmldocs_texi2html" = yes; then
+  HTMLDOCS_TEXI2HTML_TRUE=
+  HTMLDOCS_TEXI2HTML_FALSE='#'
+else
+  HTMLDOCS_TEXI2HTML_TRUE='#'
+  HTMLDOCS_TEXI2HTML_FALSE=
+fi
+
+
+htmldocs_makeinfo=no
+# Extract the first word of "makeinfo", so it can be a program name with args.
+set dummy makeinfo; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_MAKEINFO+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MAKEINFO"; then
+  ac_cv_prog_MAKEINFO="$MAKEINFO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_MAKEINFO="makeinfo"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MAKEINFO" && ac_cv_prog_MAKEINFO="false"
+fi
+fi
+MAKEINFO=$ac_cv_prog_MAKEINFO
+if test -n "$MAKEINFO"; then
+  { echo "$as_me:$LINENO: result: $MAKEINFO" >&5
+echo "${ECHO_T}$MAKEINFO" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+if test "$MAKEINFO" = "false"; then
+    { echo "$as_me:$LINENO: WARNING: ***** makeinfo utility not found *****" >&5
+echo "$as_me: WARNING: ***** makeinfo utility not found *****" >&2;}
+else
+    htmldocs_makeinfo=yes
+fi
+
+
+if test "$htmldocs_makeinfo" = yes; then
+  HTMLDOCS_MAKEINFO_TRUE=
+  HTMLDOCS_MAKEINFO_FALSE='#'
+else
+  HTMLDOCS_MAKEINFO_TRUE='#'
+  HTMLDOCS_MAKEINFO_FALSE=
+fi
+
 
 if test "$HAVE_LIBTERMCAP" = "yes"; then
     if test "$host_os" = "solaris2.3" || test "$host_os" = "solaris2.4"; then
@@ -17213,6 +17243,20 @@ if test -z "${GL_COND_LIBTOOL_TRUE}" && test -z "${GL_COND_LIBTOOL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"GL_COND_LIBTOOL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"GL_COND_LIBTOOL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HTMLDOCS_TEXI2HTML_TRUE}" && test -z "${HTMLDOCS_TEXI2HTML_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HTMLDOCS_TEXI2HTML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HTMLDOCS_TEXI2HTML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HTMLDOCS_MAKEINFO_TRUE}" && test -z "${HTMLDOCS_MAKEINFO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HTMLDOCS_MAKEINFO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HTMLDOCS_MAKEINFO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17910,6 +17954,10 @@ LIBGNU_LIBDEPS!$LIBGNU_LIBDEPS$ac_delim
 LIBGNU_LTLIBDEPS!$LIBGNU_LTLIBDEPS$ac_delim
 TEXI2DVI!$TEXI2DVI$ac_delim
 TEXI2HTML!$TEXI2HTML$ac_delim
+HTMLDOCS_TEXI2HTML_TRUE!$HTMLDOCS_TEXI2HTML_TRUE$ac_delim
+HTMLDOCS_TEXI2HTML_FALSE!$HTMLDOCS_TEXI2HTML_FALSE$ac_delim
+HTMLDOCS_MAKEINFO_TRUE!$HTMLDOCS_MAKEINFO_TRUE$ac_delim
+HTMLDOCS_MAKEINFO_FALSE!$HTMLDOCS_MAKEINFO_FALSE$ac_delim
 PRODUCT!$PRODUCT$ac_delim
 HOST!$HOST$ac_delim
 MAKE!$MAKE$ac_delim
@@ -17919,7 +17967,7 @@ CLEANFILES!$CLEANFILES$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 37; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
