remove obsolete files on install (eg $(datadir)/git/.gitrc.common)

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -408,6 +408,18 @@ EXTRA_DIST = PLATFORMS PROBLEMS LSM.in version.h.in\
 
 CONFIG_CLEAN_FILES = version.h
 distcleancheck_listfiles = find -type f -exec sh -c 'test -f $(srcdir)/{} || echo {}' ';'
+GIT_OBSOLETE = dpkg-help.txt .gitrc.aixterm .gitrc.ansi .gitrc.common	\
+ 	     .gitrc.generic .gitrc.hft .gitrc.hpterm .gitrc.linux	\
+ 	     .gitrc.linux-m .gitrc.mach .gitrc.minix .gitrc.thix	\
+ 	     .gitrc.vt100 .gitrc.vt102 .gitrc.xterm .gitrc.xterm-color	\
+ 	     .gitrc.Eterm .gitrc.console .gitrc.dtterm .gitrc.eterm	\
+ 	     .gitrc.hp .gitrc.iris-ansi .gitrc.iris-ansi-net		\
+ 	     .gitrc.pc3 .gitrc.rxvt .gitrc.screen .gitrc.sun		\
+ 	     .gitrc.sun-cmd .gitrc.vt125 .gitrc.vt200 .gitrc.vt201	\
+ 	     .gitrc.vt220 .gitrc.vt240 .gitrc.vt300 .gitrc.vt320	\
+ 	     .gitrc.vt400 .gitrc.vt420 .gitrc.xterm-debian		\
+ 	     .gitrc.xterms
+
 SUBDIRS = lib src term doc
 ACLOCAL_AMFLAGS = -I m4
 all: config.h
@@ -797,6 +809,8 @@ info: info-recursive
 info-am:
 
 install-data-am:
+	@$(NORMAL_INSTALL)
+	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
 
 install-exec-am:
 
@@ -835,10 +849,10 @@ uninstall-info: uninstall-info-recursive
 	distclean-generic distclean-hdr distclean-recursive \
 	distclean-tags distcleancheck distdir distuninstallcheck dvi \
 	dvi-am html html-am info info-am install install-am \
-	install-data install-data-am install-exec install-exec-am \
-	install-info install-info-am install-man install-strip \
-	installcheck installcheck-am installdirs installdirs-am \
-	maintainer-clean maintainer-clean-generic \
+	install-data install-data-am install-data-hook install-exec \
+	install-exec-am install-info install-info-am install-man \
+	install-strip installcheck installcheck-am installdirs \
+	installdirs-am maintainer-clean maintainer-clean-generic \
 	maintainer-clean-recursive mostlyclean mostlyclean-generic \
 	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
 	uninstall uninstall-am uninstall-info-am
@@ -849,6 +863,28 @@ html:
 
 dist-hook:
 	cp LSM gnuit.spec $(distdir)
+
+# clean up obsolete files, allow for locations with and without /share/
+install-data-hook:
+	for i in $(GIT_OBSOLETE); \
+	do\
+	    if [ -e "$(DESTDIR)$(datadir)/git/$${i}" ]; then\
+	        rm -f "$(DESTDIR)$(datadir)/git/$${i}" ];\
+	    fi;\
+	done
+	-rm -f $(DESTDIR)$(infodir)/git.info* >/dev/null 2>&1
+	-rm -f $(DESTDIR)$(prefix)/info/git.info* >/dev/null 2>&1
+	if [ -e "$(DESTDIR)$(htmldir)/git.html" ]; then \
+	    rm -f "$(DESTDIR)$(htmldir)/git.html" ];\
+	fi
+	if [ -e "$(DESTDIR)$(prefix)/doc/git.html" ]; then \
+	    rm -f "$(DESTDIR)$(prefix)/doc/git.html" ];\
+	fi
+	if [ -e "$(DESTDIR)$(prefix)/doc/git-4.3.20/git.html" ]; then \
+	    rm -f "$(DESTDIR)$(prefix)/doc/git-4.3.20/git.html" ;\
+	    rmdir "$(DESTDIR)${prefix}/doc/git-4.3.20" >/dev/null 2>&1 || true; \
+	fi
+	-rmdir "$(DESTDIR)$(datadir)/git" >/dev/null 2>&1 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
